//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatwiseSafetyDemo.Account
{


    public partial class Login
    {

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.TextBox txtUserName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUserName;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
