//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatwiseSafetyDemo.Hazards
{
    public partial class HazardList
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkExportCsv;
        protected global::System.Web.UI.WebControls.HyperLink lnkExportPdf;
        protected global::System.Web.UI.WebControls.Button btnNewHazard;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.CheckBox chkOverdue;

        protected global::System.Web.UI.WebControls.Panel pnlAssignedTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignedTo;

        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.GridView gvHazards;
    }
}
