//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatwiseSafetyDemo.Hazards
{
    public partial class HazardEdit
    {
        protected global::System.Web.UI.WebControls.Literal litHeader;
        protected global::System.Web.UI.WebControls.Literal litMeta;

        protected global::System.Web.UI.WebControls.Panel litReadOnly;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;

        protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;

        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.CustomValidator cvDueDate;

        protected global::System.Web.UI.WebControls.Button btnSuggest;

        protected global::System.Web.UI.WebControls.Panel pnlAssign;
        protected global::System.Web.UI.WebControls.Label lblAssignHeader;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignTo;
        protected global::System.Web.UI.WebControls.Literal litAssignError;
        protected global::System.Web.UI.WebControls.Button btnAssign;

        protected global::System.Web.UI.WebControls.Panel pnlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtStatusDetails;
        protected global::System.Web.UI.WebControls.Button btnChangeStatus;

        protected global::System.Web.UI.WebControls.Panel pnlComment;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.WebControls.Literal litCommentError;
        protected global::System.Web.UI.WebControls.Button btnAddComment;

        protected global::System.Web.UI.WebControls.GridView gvLogs;

        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
