//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace DatwiseSafetyDemo
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;

        protected global::System.Web.UI.WebControls.HyperLink lnkOpen;
        protected global::System.Web.UI.WebControls.HyperLink lnkInProgress;
        protected global::System.Web.UI.WebControls.HyperLink lnkResolved;
        protected global::System.Web.UI.WebControls.HyperLink lnkOverdue;

        protected global::System.Web.UI.WebControls.GridView gvBySeverity;
        protected global::System.Web.UI.WebControls.GridView gvByType;
    }
}
